name: Read Cancelled Action Notifications

on:
  schedule:
    - cron: "0 0-6 * * *"
  workflow_dispatch:

jobs:
  read-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Read notifications
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_READ_NOTIFICATIONS }}
        run: |
          gh api /notifications | \
          jq -r '.[] | select(.subject.title | contains("workflow run cancelled") or match("Attempt #\\d+ cancelled")) | .id' | \
          while read id; do
            echo "Reading notification: $id"
            gh api --method DELETE /notifications/threads/$id
          done
