name: Read Cancelled Action Notifications

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: Read notifications
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sudo apt-get install -y jq
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /notifications | \
          jq -r '.[] | select(.subject.title | contains("workflow run cancelled")) | .id' | \
          while read id; do
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /notifications/threads/$id
          done
